vibe and chat
telamon/picochat pull request #4
Opened 2021-11-02 14:29 UTC by Kanan11

2021-11-02 15:31 UTC, telamon requested changes
Awesome!!!!! :beers:

2021-11-02 15:31 UTC, telamon commented on src/frontend/components/PubPage.jsx
> +                  <h3 className='smalleTagline'>{friend.tagline}</h3>
don't use `h3` for small text. `h3` means "Header3" which makes text larger than normal.
instead use:
```jsx
<div><small>{friend.tagline}</small></div>
```
if you still need a css-class then fix case and typo: `small-tagline`

2021-11-02 15:31 UTC, telamon commented on src/frontend/components/PubPage.jsx
> +          {peers.map(friend => (
refactor for consistency:
rename `friend` => `peer`

`useFriendsList()` will be renamed in future to `usePeers()`

2021-11-02 15:31 UTC, telamon commented on src/frontend/components/Pubs.jsx
> +      console.log('pub name clicked', pub.name)
remove line 16

2021-11-02 15:31 UTC, telamon commented on src/frontend/components/Pubs.jsx
> +        console.error('faild entered Pub', err)
Fix typo `faild entered Pub` => `Failed entering pub`

2021-11-02 15:31 UTC, telamon commented on src/frontend/components/RulesPage.jsx
>        <h2>Policy of PicoChat</h2>
Replace `h2` and `h4` with:
```jsx
<h2>Disclaimer</h2>`
<p>At this point in time we have no control over any peer to peer interactions and
by design might never have.
<br />
We do not use cookies.
<br />
And we do not store any personal information.
PicoChat does not make use of a server nor a central-database.
All information that you input is in your own browser.
</p>
<p>
<sub>bottomline</sub>
<strong>We take no responsibility for how this software is used
or distributed.</strong>
<br />
<small><a href="https://github.com/telamon/picochat/issues">(any questions?)</a></small>
</p>

2021-11-02 15:31 UTC, telamon commented on public/global.css
> +.friendsList{
`.peers-list`

2021-11-03 13:40 UTC, telamon approved these changes
Good job!

2021-11-03 13:40 UTC, merged

2021-11-04 14:29 UTC, Kanan11 commented
wip is done